set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION $ENV{ANDROID_API_VERSION})
set(CMAKE_ANDROID_ARCH_ABI $ENV{ANDROID_ARCH})
set(CMAKE_ANDROID_NDK /ndk)

set(CMAKE_FIND_ROOT_PATH /depends/$ENV{ANDROID_ARCH})
